/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApoPflicht model module.
 * @module model/ApoPflicht
 * @version 0.0.1
 */
class ApoPflicht {
    /**
     * Constructs a new <code>ApoPflicht</code>.
     * @alias module:model/ApoPflicht
     * @param apopflicht {Number} apopflicht id
     * @param bedeutung {String} Bedeutung
     */
    constructor(apopflicht, bedeutung) { 
        
        ApoPflicht.initialize(this, apopflicht, bedeutung);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apopflicht, bedeutung) { 
        obj['apopflicht'] = apopflicht;
        obj['bedeutung'] = bedeutung;
    }

    /**
     * Constructs a <code>ApoPflicht</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApoPflicht} obj Optional instance to populate.
     * @return {module:model/ApoPflicht} The populated <code>ApoPflicht</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApoPflicht();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('apopflicht')) {
                obj['apopflicht'] = ApiClient.convertToType(data['apopflicht'], 'Number');
            }
            if (data.hasOwnProperty('bedeutung')) {
                obj['bedeutung'] = ApiClient.convertToType(data['bedeutung'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApoPflicht</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApoPflicht</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApoPflicht.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bedeutung'] && !(typeof data['bedeutung'] === 'string' || data['bedeutung'] instanceof String)) {
            throw new Error("Expected the field `bedeutung` to be a primitive type in the JSON string but got " + data['bedeutung']);
        }

        return true;
    }


}

ApoPflicht.RequiredProperties = ["apopflicht", "bedeutung"];

/**
 * @member {Date} created_at
 */
ApoPflicht.prototype['created_at'] = undefined;

/**
 * apopflicht id
 * @member {Number} apopflicht
 */
ApoPflicht.prototype['apopflicht'] = undefined;

/**
 * Bedeutung
 * @member {String} bedeutung
 */
ApoPflicht.prototype['bedeutung'] = undefined;






export default ApoPflicht;

