/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Applikationsform model module.
 * @module model/Applikationsform
 * @version 0.0.1
 */
class Applikationsform {
    /**
     * Constructs a new <code>Applikationsform</code>.
     * @alias module:model/Applikationsform
     * @param aiVersionId {String} Foreing key to 'AiDataVersion' ('GKV WiDo Arzneimittel Index' Data Format Version) which contains the information which Arzneimittel Index 'Datenstand' and 'Dateiversion' the row has
     * @param appform {String} Applikationsform
     * @param bedeutung {String} Bedeutung
     */
    constructor(aiVersionId, appform, bedeutung) { 
        
        Applikationsform.initialize(this, aiVersionId, appform, bedeutung);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, aiVersionId, appform, bedeutung) { 
        obj['ai_version_id'] = aiVersionId;
        obj['appform'] = appform;
        obj['bedeutung'] = bedeutung;
    }

    /**
     * Constructs a <code>Applikationsform</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Applikationsform} obj Optional instance to populate.
     * @return {module:model/Applikationsform} The populated <code>Applikationsform</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Applikationsform();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('ai_version_id')) {
                obj['ai_version_id'] = ApiClient.convertToType(data['ai_version_id'], 'String');
            }
            if (data.hasOwnProperty('appform')) {
                obj['appform'] = ApiClient.convertToType(data['appform'], 'String');
            }
            if (data.hasOwnProperty('bedeutung')) {
                obj['bedeutung'] = ApiClient.convertToType(data['bedeutung'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Applikationsform</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Applikationsform</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Applikationsform.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ai_version_id'] && !(typeof data['ai_version_id'] === 'string' || data['ai_version_id'] instanceof String)) {
            throw new Error("Expected the field `ai_version_id` to be a primitive type in the JSON string but got " + data['ai_version_id']);
        }
        // ensure the json data is a string
        if (data['appform'] && !(typeof data['appform'] === 'string' || data['appform'] instanceof String)) {
            throw new Error("Expected the field `appform` to be a primitive type in the JSON string but got " + data['appform']);
        }
        // ensure the json data is a string
        if (data['bedeutung'] && !(typeof data['bedeutung'] === 'string' || data['bedeutung'] instanceof String)) {
            throw new Error("Expected the field `bedeutung` to be a primitive type in the JSON string but got " + data['bedeutung']);
        }

        return true;
    }


}

Applikationsform.RequiredProperties = ["ai_version_id", "appform", "bedeutung"];

/**
 * @member {Date} created_at
 */
Applikationsform.prototype['created_at'] = undefined;

/**
 * Foreing key to 'AiDataVersion' ('GKV WiDo Arzneimittel Index' Data Format Version) which contains the information which Arzneimittel Index 'Datenstand' and 'Dateiversion' the row has
 * @member {String} ai_version_id
 */
Applikationsform.prototype['ai_version_id'] = undefined;

/**
 * Applikationsform
 * @member {String} appform
 */
Applikationsform.prototype['appform'] = undefined;

/**
 * Bedeutung
 * @member {String} bedeutung
 */
Applikationsform.prototype['bedeutung'] = undefined;






export default Applikationsform;

