/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Biosimilar model module.
 * @module model/Biosimilar
 * @version 0.0.1
 */
class Biosimilar {
    /**
     * Constructs a new <code>Biosimilar</code>.
     * @alias module:model/Biosimilar
     * @param biosimilar {String} biosimilar id
     * @param bedeutung {String} Bedeutung
     */
    constructor(biosimilar, bedeutung) { 
        
        Biosimilar.initialize(this, biosimilar, bedeutung);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, biosimilar, bedeutung) { 
        obj['biosimilar'] = biosimilar;
        obj['bedeutung'] = bedeutung;
    }

    /**
     * Constructs a <code>Biosimilar</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Biosimilar} obj Optional instance to populate.
     * @return {module:model/Biosimilar} The populated <code>Biosimilar</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Biosimilar();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('biosimilar')) {
                obj['biosimilar'] = ApiClient.convertToType(data['biosimilar'], 'String');
            }
            if (data.hasOwnProperty('bedeutung')) {
                obj['bedeutung'] = ApiClient.convertToType(data['bedeutung'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Biosimilar</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Biosimilar</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Biosimilar.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['biosimilar'] && !(typeof data['biosimilar'] === 'string' || data['biosimilar'] instanceof String)) {
            throw new Error("Expected the field `biosimilar` to be a primitive type in the JSON string but got " + data['biosimilar']);
        }
        // ensure the json data is a string
        if (data['bedeutung'] && !(typeof data['bedeutung'] === 'string' || data['bedeutung'] instanceof String)) {
            throw new Error("Expected the field `bedeutung` to be a primitive type in the JSON string but got " + data['bedeutung']);
        }

        return true;
    }


}

Biosimilar.RequiredProperties = ["biosimilar", "bedeutung"];

/**
 * @member {Date} created_at
 */
Biosimilar.prototype['created_at'] = undefined;

/**
 * biosimilar id
 * @member {String} biosimilar
 */
Biosimilar.prototype['biosimilar'] = undefined;

/**
 * Bedeutung
 * @member {String} bedeutung
 */
Biosimilar.prototype['bedeutung'] = undefined;






export default Biosimilar;

