/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Completed from './Completed';

/**
 * The Event model module.
 * @module model/Event
 * @version 0.0.1
 */
class Event {
    /**
     * Constructs a new <code>Event</code>.
     * @alias module:model/Event
     * @param studyId {String} 
     */
    constructor(studyId) { 
        
        Event.initialize(this, studyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, studyId) { 
        obj['study_id'] = studyId;
    }

    /**
     * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Event} obj Optional instance to populate.
     * @return {module:model/Event} The populated <code>Event</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Event();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('completed')) {
                obj['completed'] = Completed.constructFromObject(data['completed']);
            }
            if (data.hasOwnProperty('study_id')) {
                obj['study_id'] = ApiClient.convertToType(data['study_id'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Event</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Event</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Event.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `completed`
        if (data['completed']) { // data not null
          Completed.validateJSON(data['completed']);
        }
        // ensure the json data is a string
        if (data['study_id'] && !(typeof data['study_id'] === 'string' || data['study_id'] instanceof String)) {
            throw new Error("Expected the field `study_id` to be a primitive type in the JSON string but got " + data['study_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

Event.RequiredProperties = ["study_id"];

/**
 * @member {Date} created_at
 */
Event.prototype['created_at'] = undefined;

/**
 * @member {String} name
 */
Event.prototype['name'] = undefined;

/**
 * @member {module:model/Completed} completed
 */
Event.prototype['completed'] = undefined;

/**
 * @member {String} study_id
 */
Event.prototype['study_id'] = undefined;

/**
 * @member {String} id
 */
Event.prototype['id'] = undefined;






export default Event;

