/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AsNeededDoseUnit from './AsNeededDoseUnit';
import ConsumedMedsTodayAnswers from './ConsumedMedsTodayAnswers';
import DosePerDay from './DosePerDay';
import IntakeAdministeredByDoctor from './IntakeAdministeredByDoctor';
import IntakeEndTimeUtc from './IntakeEndTimeUtc';
import IntakeIntakeRegularOrAsNeeded from './IntakeIntakeRegularOrAsNeeded';
import IntakeRegularIntervallOfDailyDose from './IntakeRegularIntervallOfDailyDose';

/**
 * The Intake model module.
 * @module model/Intake
 * @version 0.0.1
 */
class Intake {
    /**
     * Constructs a new <code>Intake</code>.
     * @alias module:model/Intake
     * @param interviewId {String} 
     * @param pharmazentralnummer {String} Pharmazentralnummer as 8 digits only
     * @param intakeStartTimeUtc {Date} 
     * @param asNeededDoseUnit {module:model/AsNeededDoseUnit} 
     * @param consumedMedsToday {module:model/ConsumedMedsTodayAnswers} 
     */
    constructor(interviewId, pharmazentralnummer, intakeStartTimeUtc, asNeededDoseUnit, consumedMedsToday) { 
        
        Intake.initialize(this, interviewId, pharmazentralnummer, intakeStartTimeUtc, asNeededDoseUnit, consumedMedsToday);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, interviewId, pharmazentralnummer, intakeStartTimeUtc, asNeededDoseUnit, consumedMedsToday) { 
        obj['interview_id'] = interviewId;
        obj['pharmazentralnummer'] = pharmazentralnummer;
        obj['intake_start_time_utc'] = intakeStartTimeUtc;
        obj['as_needed_dose_unit'] = asNeededDoseUnit;
        obj['consumed_meds_today'] = consumedMedsToday;
    }

    /**
     * Constructs a <code>Intake</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Intake} obj Optional instance to populate.
     * @return {module:model/Intake} The populated <code>Intake</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Intake();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('interview_id')) {
                obj['interview_id'] = ApiClient.convertToType(data['interview_id'], 'String');
            }
            if (data.hasOwnProperty('pharmazentralnummer')) {
                obj['pharmazentralnummer'] = ApiClient.convertToType(data['pharmazentralnummer'], 'String');
            }
            if (data.hasOwnProperty('intake_start_time_utc')) {
                obj['intake_start_time_utc'] = ApiClient.convertToType(data['intake_start_time_utc'], 'Date');
            }
            if (data.hasOwnProperty('intake_end_time_utc')) {
                obj['intake_end_time_utc'] = IntakeEndTimeUtc.constructFromObject(data['intake_end_time_utc']);
            }
            if (data.hasOwnProperty('administered_by_doctor')) {
                obj['administered_by_doctor'] = IntakeAdministeredByDoctor.constructFromObject(data['administered_by_doctor']);
            }
            if (data.hasOwnProperty('intake_regular_or_as_needed')) {
                obj['intake_regular_or_as_needed'] = IntakeIntakeRegularOrAsNeeded.constructFromObject(data['intake_regular_or_as_needed']);
            }
            if (data.hasOwnProperty('dose_per_day')) {
                obj['dose_per_day'] = DosePerDay.constructFromObject(data['dose_per_day']);
            }
            if (data.hasOwnProperty('regular_intervall_of_daily_dose')) {
                obj['regular_intervall_of_daily_dose'] = IntakeRegularIntervallOfDailyDose.constructFromObject(data['regular_intervall_of_daily_dose']);
            }
            if (data.hasOwnProperty('as_needed_dose_unit')) {
                obj['as_needed_dose_unit'] = AsNeededDoseUnit.constructFromObject(data['as_needed_dose_unit']);
            }
            if (data.hasOwnProperty('consumed_meds_today')) {
                obj['consumed_meds_today'] = ConsumedMedsTodayAnswers.constructFromObject(data['consumed_meds_today']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Intake</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Intake</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Intake.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['interview_id'] && !(typeof data['interview_id'] === 'string' || data['interview_id'] instanceof String)) {
            throw new Error("Expected the field `interview_id` to be a primitive type in the JSON string but got " + data['interview_id']);
        }
        // ensure the json data is a string
        if (data['pharmazentralnummer'] && !(typeof data['pharmazentralnummer'] === 'string' || data['pharmazentralnummer'] instanceof String)) {
            throw new Error("Expected the field `pharmazentralnummer` to be a primitive type in the JSON string but got " + data['pharmazentralnummer']);
        }
        // validate the optional field `intake_end_time_utc`
        if (data['intake_end_time_utc']) { // data not null
          IntakeEndTimeUtc.validateJSON(data['intake_end_time_utc']);
        }
        // validate the optional field `administered_by_doctor`
        if (data['administered_by_doctor']) { // data not null
          IntakeAdministeredByDoctor.validateJSON(data['administered_by_doctor']);
        }
        // validate the optional field `intake_regular_or_as_needed`
        if (data['intake_regular_or_as_needed']) { // data not null
          IntakeIntakeRegularOrAsNeeded.validateJSON(data['intake_regular_or_as_needed']);
        }
        // validate the optional field `dose_per_day`
        if (data['dose_per_day']) { // data not null
          DosePerDay.validateJSON(data['dose_per_day']);
        }
        // validate the optional field `regular_intervall_of_daily_dose`
        if (data['regular_intervall_of_daily_dose']) { // data not null
          IntakeRegularIntervallOfDailyDose.validateJSON(data['regular_intervall_of_daily_dose']);
        }
        // validate the optional field `as_needed_dose_unit`
        if (data['as_needed_dose_unit']) { // data not null
          AsNeededDoseUnit.validateJSON(data['as_needed_dose_unit']);
        }

        return true;
    }


}

Intake.RequiredProperties = ["interview_id", "pharmazentralnummer", "intake_start_time_utc", "as_needed_dose_unit", "consumed_meds_today"];

/**
 * @member {Date} created_at
 */
Intake.prototype['created_at'] = undefined;

/**
 * @member {String} id
 */
Intake.prototype['id'] = undefined;

/**
 * @member {String} interview_id
 */
Intake.prototype['interview_id'] = undefined;

/**
 * Pharmazentralnummer as 8 digits only
 * @member {String} pharmazentralnummer
 */
Intake.prototype['pharmazentralnummer'] = undefined;

/**
 * @member {Date} intake_start_time_utc
 */
Intake.prototype['intake_start_time_utc'] = undefined;

/**
 * @member {module:model/IntakeEndTimeUtc} intake_end_time_utc
 */
Intake.prototype['intake_end_time_utc'] = undefined;

/**
 * @member {module:model/IntakeAdministeredByDoctor} administered_by_doctor
 */
Intake.prototype['administered_by_doctor'] = undefined;

/**
 * @member {module:model/IntakeIntakeRegularOrAsNeeded} intake_regular_or_as_needed
 */
Intake.prototype['intake_regular_or_as_needed'] = undefined;

/**
 * @member {module:model/DosePerDay} dose_per_day
 */
Intake.prototype['dose_per_day'] = undefined;

/**
 * @member {module:model/IntakeRegularIntervallOfDailyDose} regular_intervall_of_daily_dose
 */
Intake.prototype['regular_intervall_of_daily_dose'] = undefined;

/**
 * @member {module:model/AsNeededDoseUnit} as_needed_dose_unit
 */
Intake.prototype['as_needed_dose_unit'] = undefined;

/**
 * @member {module:model/ConsumedMedsTodayAnswers} consumed_meds_today
 */
Intake.prototype['consumed_meds_today'] = undefined;






export default Intake;

