/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class IntervalOfDailyDoseAnswers.
* @enum {}
* @readonly
*/
export default class IntervalOfDailyDoseAnswers {
    
        /**
         * value: "regular"
         * @const
         */
        "regular" = "regular";

    
        /**
         * value: "as needed"
         * @const
         */
        "as needed" = "as needed";

    
        /**
         * value: "every 2. day"
         * @const
         */
        "every 2. day" = "every 2. day";

    
        /**
         * value: "every 3. day"
         * @const
         */
        "every 3. day" = "every 3. day";

    
        /**
         * value: "every 4. day / twice a week"
         * @const
         */
        "every 4. day / twice a week" = "every 4. day / twice a week";

    
        /**
         * value: "intervals of one week or more"
         * @const
         */
        "intervals of one week or more" = "intervals of one week or more";

    

    /**
    * Returns a <code>IntervalOfDailyDoseAnswers</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/IntervalOfDailyDoseAnswers} The enum <code>IntervalOfDailyDoseAnswers</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

