/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JWTAccessTokenResponse model module.
 * @module model/JWTAccessTokenResponse
 * @version 0.0.1
 */
class JWTAccessTokenResponse {
    /**
     * Constructs a new <code>JWTAccessTokenResponse</code>.
     * @alias module:model/JWTAccessTokenResponse
     * @param expiresIn {Number} The number of seconds until the token expires
     * @param expiresAt {Number} The time as POSIX timestamp in UTC when the token expires
     * @param accessToken {String} Token to be used to authenticate against the API
     */
    constructor(expiresIn, expiresAt, accessToken) { 
        
        JWTAccessTokenResponse.initialize(this, expiresIn, expiresAt, accessToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, expiresIn, expiresAt, accessToken) { 
        obj['expires_in'] = expiresIn;
        obj['expires_at'] = expiresAt;
        obj['access_token'] = accessToken;
    }

    /**
     * Constructs a <code>JWTAccessTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JWTAccessTokenResponse} obj Optional instance to populate.
     * @return {module:model/JWTAccessTokenResponse} The populated <code>JWTAccessTokenResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JWTAccessTokenResponse();

            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], Object);
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'Number');
            }
            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JWTAccessTokenResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JWTAccessTokenResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JWTAccessTokenResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['access_token'] && !(typeof data['access_token'] === 'string' || data['access_token'] instanceof String)) {
            throw new Error("Expected the field `access_token` to be a primitive type in the JSON string but got " + data['access_token']);
        }

        return true;
    }


}

JWTAccessTokenResponse.RequiredProperties = ["expires_in", "expires_at", "access_token"];

/**
 * @member {Object} token_type
 */
JWTAccessTokenResponse.prototype['token_type'] = undefined;

/**
 * The number of seconds until the token expires
 * @member {Number} expires_in
 */
JWTAccessTokenResponse.prototype['expires_in'] = undefined;

/**
 * The time as POSIX timestamp in UTC when the token expires
 * @member {Number} expires_at
 */
JWTAccessTokenResponse.prototype['expires_at'] = undefined;

/**
 * Token to be used to authenticate against the API
 * @member {String} access_token
 */
JWTAccessTokenResponse.prototype['access_token'] = undefined;






export default JWTAccessTokenResponse;

