/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StudyPermissonUpdate model module.
 * @module model/StudyPermissonUpdate
 * @version 0.0.1
 */
class StudyPermissonUpdate {
    /**
     * Constructs a new <code>StudyPermissonUpdate</code>.
     * @alias module:model/StudyPermissonUpdate
     */
    constructor() { 
        
        StudyPermissonUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StudyPermissonUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StudyPermissonUpdate} obj Optional instance to populate.
     * @return {module:model/StudyPermissonUpdate} The populated <code>StudyPermissonUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudyPermissonUpdate();

            if (data.hasOwnProperty('is_study_viewer')) {
                obj['is_study_viewer'] = ApiClient.convertToType(data['is_study_viewer'], 'Boolean');
            }
            if (data.hasOwnProperty('is_study_interviewer')) {
                obj['is_study_interviewer'] = ApiClient.convertToType(data['is_study_interviewer'], 'Boolean');
            }
            if (data.hasOwnProperty('is_study_admin')) {
                obj['is_study_admin'] = ApiClient.convertToType(data['is_study_admin'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StudyPermissonUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StudyPermissonUpdate</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * This is the minimal access to a study. The user can see all data but can not alter anything
 * @member {Boolean} is_study_viewer
 * @default true
 */
StudyPermissonUpdate.prototype['is_study_viewer'] = true;

/**
 * Study interviewers can create new interview entries for this study.
 * @member {Boolean} is_study_interviewer
 * @default false
 */
StudyPermissonUpdate.prototype['is_study_interviewer'] = false;

/**
 * Study admins can give access to the study to new users.
 * @member {Boolean} is_study_admin
 * @default false
 */
StudyPermissonUpdate.prototype['is_study_admin'] = false;






export default StudyPermissonUpdate;

