/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DisplayName1 from './DisplayName1';
import Email from './Email';
import Id from './Id';

/**
 * The UserUpdateByAdmin model module.
 * @module model/UserUpdateByAdmin
 * @version 0.0.1
 */
class UserUpdateByAdmin {
    /**
     * Constructs a new <code>UserUpdateByAdmin</code>.
     * @alias module:model/UserUpdateByAdmin
     */
    constructor() { 
        
        UserUpdateByAdmin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserUpdateByAdmin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserUpdateByAdmin} obj Optional instance to populate.
     * @return {module:model/UserUpdateByAdmin} The populated <code>UserUpdateByAdmin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserUpdateByAdmin();

            if (data.hasOwnProperty('email')) {
                obj['email'] = Email.constructFromObject(data['email']);
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = DisplayName1.constructFromObject(data['display_name']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = Id.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
            }
            if (data.hasOwnProperty('deactivated')) {
                obj['deactivated'] = ApiClient.convertToType(data['deactivated'], 'Boolean');
            }
            if (data.hasOwnProperty('is_email_verified')) {
                obj['is_email_verified'] = ApiClient.convertToType(data['is_email_verified'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserUpdateByAdmin</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserUpdateByAdmin</code>.
     */
    static validateJSON(data) {
        // validate the optional field `email`
        if (data['email']) { // data not null
          Email.validateJSON(data['email']);
        }
        // validate the optional field `display_name`
        if (data['display_name']) { // data not null
          DisplayName1.validateJSON(data['display_name']);
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          Id.validateJSON(data['id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['roles'])) {
            throw new Error("Expected the field `roles` to be an array in the JSON data but got " + data['roles']);
        }

        return true;
    }


}



/**
 * @member {module:model/Email} email
 */
UserUpdateByAdmin.prototype['email'] = undefined;

/**
 * @member {module:model/DisplayName1} display_name
 */
UserUpdateByAdmin.prototype['display_name'] = undefined;

/**
 * @member {module:model/Id} id
 */
UserUpdateByAdmin.prototype['id'] = undefined;

/**
 * @member {Array.<String>} roles
 */
UserUpdateByAdmin.prototype['roles'] = undefined;

/**
 * @member {Boolean} deactivated
 * @default false
 */
UserUpdateByAdmin.prototype['deactivated'] = false;

/**
 * @member {Boolean} is_email_verified
 * @default false
 */
UserUpdateByAdmin.prototype['is_email_verified'] = false;






export default UserUpdateByAdmin;

