/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DisplayName1 from './DisplayName1';
import Email from './Email';

/**
 * The UserUpdateByUser model module.
 * @module model/UserUpdateByUser
 * @version 0.0.1
 */
class UserUpdateByUser {
    /**
     * Constructs a new <code>UserUpdateByUser</code>.
     * @alias module:model/UserUpdateByUser
     */
    constructor() { 
        
        UserUpdateByUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserUpdateByUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserUpdateByUser} obj Optional instance to populate.
     * @return {module:model/UserUpdateByUser} The populated <code>UserUpdateByUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserUpdateByUser();

            if (data.hasOwnProperty('email')) {
                obj['email'] = Email.constructFromObject(data['email']);
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = DisplayName1.constructFromObject(data['display_name']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserUpdateByUser</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserUpdateByUser</code>.
     */
    static validateJSON(data) {
        // validate the optional field `email`
        if (data['email']) { // data not null
          Email.validateJSON(data['email']);
        }
        // validate the optional field `display_name`
        if (data['display_name']) { // data not null
          DisplayName1.validateJSON(data['display_name']);
        }

        return true;
    }


}



/**
 * @member {module:model/Email} email
 */
UserUpdateByUser.prototype['email'] = undefined;

/**
 * @member {module:model/DisplayName1} display_name
 */
UserUpdateByUser.prototype['display_name'] = undefined;






export default UserUpdateByUser;

