[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "medlogserver"
authors = [{ name = "Tim Bleimehl", email = "bleimehl@helmholtz-munich.de" }]
description = "A Rest API Server on a Postgres DB to store the medical history of study participants."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["DZD", "MedLog"]
license = { text = "MIT" }
classifiers = [
    "Framework :: FastAPI",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "uvicorn",
    "fastapi",
    "Authlib",
    "httpx",
    "sqlmodel",
    "itsdangerous",
    "pyyaml",
    "pydantic",
    "pydantic_settings",
    "Click",
    "getversion",
    "pip-tools"
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest", "deepdiff"]
docs = ["mkdocs", "mkdocstrings[python]", "mkdocs-autorefs", "mkdocs-material"]
[project.scripts]
medlogserver = "medlogserver.main:start"
