FROM alpine
#FROM node:20


RUN apk add nodejs npm

RUN mkdir -p /app
WORKDIR /app
COPY frontend /app
RUN npm install
RUN npm run prod
#RUN mkdir -p /config


EXPOSE 8081

#CMD ["npm", "start" , "--" ,"--port", "8081", "--host", "0.0.0.0"]
CMD ["sh", "-c", "npm start -- --port ${PORT:-8081} --host 0.0.0.0"]
