/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.DrugApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DrugApi', function() {
    describe('getDrugDrugByPznPznGet', function() {
      it('should call getDrugDrugByPznPznGet successfully', function(done) {
        //uncomment below and update the code to test getDrugDrugByPznPznGet
        //instance.getDrugDrugByPznPznGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listApopflichtDrugEnumApopflichtGet', function() {
      it('should call listApopflichtDrugEnumApopflichtGet successfully', function(done) {
        //uncomment below and update the code to test listApopflichtDrugEnumApopflichtGet
        //instance.listApopflichtDrugEnumApopflichtGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listApopflichtDrugEnumPreisartGet', function() {
      it('should call listApopflichtDrugEnumPreisartGet successfully', function(done) {
        //uncomment below and update the code to test listApopflichtDrugEnumPreisartGet
        //instance.listApopflichtDrugEnumPreisartGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listApplikationsformsDrugEnumAppformGet', function() {
      it('should call listApplikationsformsDrugEnumAppformGet successfully', function(done) {
        //uncomment below and update the code to test listApplikationsformsDrugEnumAppformGet
        //instance.listApplikationsformsDrugEnumAppformGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listApplikationsformsDrugEnumAppformKeyGet', function() {
      it('should call listApplikationsformsDrugEnumAppformKeyGet successfully', function(done) {
        //uncomment below and update the code to test listApplikationsformsDrugEnumAppformKeyGet
        //instance.listApplikationsformsDrugEnumAppformKeyGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDarreichungsformsDrugEnumDarrformGet', function() {
      it('should call listDarreichungsformsDrugEnumDarrformGet successfully', function(done) {
        //uncomment below and update the code to test listDarreichungsformsDrugEnumDarrformGet
        //instance.listDarreichungsformsDrugEnumDarrformGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDrugsDrugGet', function() {
      it('should call listDrugsDrugGet successfully', function(done) {
        //uncomment below and update the code to test listDrugsDrugGet
        //instance.listDrugsDrugGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listGenerikakennsDrugEnumGenerikakennGet', function() {
      it('should call listGenerikakennsDrugEnumGenerikakennGet successfully', function(done) {
        //uncomment below and update the code to test listGenerikakennsDrugEnumGenerikakennGet
        //instance.listGenerikakennsDrugEnumGenerikakennGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPackgroesseDrugEnumNormpackungsgroessenGet', function() {
      it('should call listPackgroesseDrugEnumNormpackungsgroessenGet successfully', function(done) {
        //uncomment below and update the code to test listPackgroesseDrugEnumNormpackungsgroessenGet
        //instance.listPackgroesseDrugEnumNormpackungsgroessenGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchDrugsDrugSearchGet', function() {
      it('should call searchDrugsDrugSearchGet successfully', function(done) {
        //uncomment below and update the code to test searchDrugsDrugSearchGet
        //instance.searchDrugsDrugSearchGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
