/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.InterviewApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InterviewApi', function() {
    describe('createInterviewStudyStudyIdEventEventIdInterviewPost', function() {
      it('should call createInterviewStudyStudyIdEventEventIdInterviewPost successfully', function(done) {
        //uncomment below and update the code to test createInterviewStudyStudyIdEventEventIdInterviewPost
        //instance.createInterviewStudyStudyIdEventEventIdInterviewPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteInterviewStudyStudyIdEventEventIdInterviewInterviewIdDelete', function() {
      it('should call deleteInterviewStudyStudyIdEventEventIdInterviewInterviewIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteInterviewStudyStudyIdEventEventIdInterviewInterviewIdDelete
        //instance.deleteInterviewStudyStudyIdEventEventIdInterviewInterviewIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getInterviewStudyStudyIdEventEventIdInterviewInterviewIdGet', function() {
      it('should call getInterviewStudyStudyIdEventEventIdInterviewInterviewIdGet successfully', function(done) {
        //uncomment below and update the code to test getInterviewStudyStudyIdEventEventIdInterviewInterviewIdGet
        //instance.getInterviewStudyStudyIdEventEventIdInterviewInterviewIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastGet', function() {
      it('should call getLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastGet successfully', function(done) {
        //uncomment below and update the code to test getLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastGet
        //instance.getLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLastNonCompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentGet', function() {
      it('should call getLastNonCompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentGet successfully', function(done) {
        //uncomment below and update the code to test getLastNonCompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentGet
        //instance.getLastNonCompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllInterviewsOfStudyStudyStudyIdInterviewGet', function() {
      it('should call listAllInterviewsOfStudyStudyStudyIdInterviewGet successfully', function(done) {
        //uncomment below and update the code to test listAllInterviewsOfStudyStudyStudyIdInterviewGet
        //instance.listAllInterviewsOfStudyStudyStudyIdInterviewGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listInterviewsByStudyEventStudyStudyIdEventEventIdInterviewGet', function() {
      it('should call listInterviewsByStudyEventStudyStudyIdEventEventIdInterviewGet successfully', function(done) {
        //uncomment below and update the code to test listInterviewsByStudyEventStudyStudyIdEventEventIdInterviewGet
        //instance.listInterviewsByStudyEventStudyStudyIdEventEventIdInterviewGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listInterviewsOfProbandStudyStudyIdProbandProbandIdInterviewGet', function() {
      it('should call listInterviewsOfProbandStudyStudyIdProbandProbandIdInterviewGet successfully', function(done) {
        //uncomment below and update the code to test listInterviewsOfProbandStudyStudyIdProbandProbandIdInterviewGet
        //instance.listInterviewsOfProbandStudyStudyIdProbandProbandIdInterviewGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateInterviewStudyStudyIdEventEventIdInterviewInterviewIdPatch', function() {
      it('should call updateInterviewStudyStudyIdEventEventIdInterviewInterviewIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateInterviewStudyStudyIdEventEventIdInterviewInterviewIdPatch
        //instance.updateInterviewStudyStudyIdEventEventIdInterviewInterviewIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
