/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.StudyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StudyApi', function() {
    describe('createStudyStudyPost', function() {
      it('should call createStudyStudyPost successfully', function(done) {
        //uncomment below and update the code to test createStudyStudyPost
        //instance.createStudyStudyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteStudyStudyStudyIdDelete', function() {
      it('should call deleteStudyStudyStudyIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteStudyStudyStudyIdDelete
        //instance.deleteStudyStudyStudyIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listStudiesStudyGet', function() {
      it('should call listStudiesStudyGet successfully', function(done) {
        //uncomment below and update the code to test listStudiesStudyGet
        //instance.listStudiesStudyGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStudyStudyStudyIdPatch', function() {
      it('should call updateStudyStudyStudyIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateStudyStudyStudyIdPatch
        //instance.updateStudyStudyStudyIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
