"""Automated migration: Hotfix for obsolete passlib

Revision ID: 328eaf68f1a1
Revises: e1d280620446
Create Date: 2025-11-21 16:34:02.060238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = "328eaf68f1a1"
down_revision: Union[str, Sequence[str], None] = "e1d280620446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column(
            "user_auth",
            "salt",
            existing_type=sa.VARCHAR(),
            type_=sa.LargeBinary(),
            existing_nullable=False,
            postgresql_using="encode(salt::bytea, 'escape')::bytea",
        )
        # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table("user_auth", recreate="always") as batch_op:
            batch_op.alter_column(
                "salt",
                existing_type=sa.VARCHAR(),
                type_=sa.LargeBinary(),
                existing_nullable=False,
            )
        # ### end Alembic commands ###
    else:
        raise NotImplementedError(
            f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'"
        )


def downgrade():
    raise NotImplementedError(f"DZDMedLog does not support downgrading the database")
