/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AdministeredByDoctorAnswers.
* @enum {}
* @readonly
*/
export default class AdministeredByDoctorAnswers {
    
        /**
         * value: "prescribed"
         * @const
         */
        "prescribed" = "prescribed";

    
        /**
         * value: "recommended"
         * @const
         */
        "recommended" = "recommended";

    
        /**
         * value: "no"
         * @const
         */
        "no" = "no";

    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    

    /**
    * Returns a <code>AdministeredByDoctorAnswers</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AdministeredByDoctorAnswers} The enum <code>AdministeredByDoctorAnswers</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

