/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.InterviewUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InterviewUpdate', function() {
    it('should create an instance of InterviewUpdate', function() {
      // uncomment below and update the code to test InterviewUpdate
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be.a(MedLogRestApi.InterviewUpdate);
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be();
    });

    it('should have the property probandExternalId (base name: "proband_external_id")', function() {
      // uncomment below and update the code to test the property probandExternalId
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be();
    });

    it('should have the property interviewStartTimeUtc (base name: "interview_start_time_utc")', function() {
      // uncomment below and update the code to test the property interviewStartTimeUtc
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be();
    });

    it('should have the property interviewEndTimeUtc (base name: "interview_end_time_utc")', function() {
      // uncomment below and update the code to test the property interviewEndTimeUtc
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be();
    });

    it('should have the property probandHasTakenMeds (base name: "proband_has_taken_meds")', function() {
      // uncomment below and update the code to test the property probandHasTakenMeds
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be();
    });

    it('should have the property interviewNumber (base name: "interview_number")', function() {
      // uncomment below and update the code to test the property interviewNumber
      //var instance = new MedLogRestApi.InterviewUpdate();
      //expect(instance).to.be();
    });

  });

}));
