/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.MedLogSearchEngineResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MedLogSearchEngineResult', function() {
    it('should create an instance of MedLogSearchEngineResult', function() {
      // uncomment below and update the code to test MedLogSearchEngineResult
      //var instance = new MedLogRestApi.MedLogSearchEngineResult();
      //expect(instance).to.be.a(MedLogRestApi.MedLogSearchEngineResult);
    });

    it('should have the property pzn (base name: "pzn")', function() {
      // uncomment below and update the code to test the property pzn
      //var instance = new MedLogRestApi.MedLogSearchEngineResult();
      //expect(instance).to.be();
    });

    it('should have the property relevanceScore (base name: "relevance_score")', function() {
      // uncomment below and update the code to test the property relevanceScore
      //var instance = new MedLogRestApi.MedLogSearchEngineResult();
      //expect(instance).to.be();
    });

    it('should have the property item (base name: "item")', function() {
      // uncomment below and update the code to test the property item
      //var instance = new MedLogRestApi.MedLogSearchEngineResult();
      //expect(instance).to.be();
    });

  });

}));
