/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.StudyUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StudyUpdate', function() {
    it('should create an instance of StudyUpdate', function() {
      // uncomment below and update the code to test StudyUpdate
      //var instance = new MedLogRestApi.StudyUpdate();
      //expect(instance).to.be.a(MedLogRestApi.StudyUpdate);
    });

    it('should have the property displayName (base name: "display_name")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new MedLogRestApi.StudyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property deactivated (base name: "deactivated")', function() {
      // uncomment below and update the code to test the property deactivated
      //var instance = new MedLogRestApi.StudyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property noPermissions (base name: "no_permissions")', function() {
      // uncomment below and update the code to test the property noPermissions
      //var instance = new MedLogRestApi.StudyUpdate();
      //expect(instance).to.be();
    });

  });

}));
