/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedLogRestApi);
  }
}(this, function(expect, MedLogRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MedLogRestApi.IntakeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IntakeApi', function() {
    describe('createIntakeStudyStudyIdInterviewInterviewIdIntakePost', function() {
      it('should call createIntakeStudyStudyIdInterviewInterviewIdIntakePost successfully', function(done) {
        //uncomment below and update the code to test createIntakeStudyStudyIdInterviewInterviewIdIntakePost
        //instance.createIntakeStudyStudyIdInterviewInterviewIdIntakePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdDelete', function() {
      it('should call deleteIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdDelete
        //instance.deleteIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdGet', function() {
      it('should call getIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdGet successfully', function(done) {
        //uncomment below and update the code to test getIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdGet
        //instance.getIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllIntakesOfInterviewStudyStudyIdInterviewInterviewIdIntakeGet', function() {
      it('should call listAllIntakesOfInterviewStudyStudyIdInterviewInterviewIdIntakeGet successfully', function(done) {
        //uncomment below and update the code to test listAllIntakesOfInterviewStudyStudyIdInterviewInterviewIdIntakeGet
        //instance.listAllIntakesOfInterviewStudyStudyIdInterviewInterviewIdIntakeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllIntakesOfLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastIntakeGet', function() {
      it('should call listAllIntakesOfLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastIntakeGet successfully', function(done) {
        //uncomment below and update the code to test listAllIntakesOfLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastIntakeGet
        //instance.listAllIntakesOfLastCompletedInterviewStudyStudyIdProbandProbandIdInterviewLastIntakeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllIntakesOfLastUncompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentIntakeGet', function() {
      it('should call listAllIntakesOfLastUncompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentIntakeGet successfully', function(done) {
        //uncomment below and update the code to test listAllIntakesOfLastUncompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentIntakeGet
        //instance.listAllIntakesOfLastUncompletedInterviewStudyStudyIdProbandProbandIdInterviewCurrentIntakeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdPatch', function() {
      it('should call updateIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdPatch
        //instance.updateIntakeStudyStudyIdInterviewInterviewIdIntakeIntakeIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
