"""new drug field attr

Revision ID: 20174de3bd79
Revises: f5d8639f63da
Create Date: 2025-12-09 15:02:36.337796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = "20174de3bd79"
down_revision: Union[str, Sequence[str], None] = "f5d8639f63da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        displaypriorityclass_enum = sa.Enum(
            "CLASS1", "CLASS2", "CLASS3", name="displaypriorityclass"
        )
        displaypriorityclass_enum.create(op.get_bind(), checkfirst=True)
        op.add_column(
            "drug_attr_field_definition",
            sa.Column(
                "field_display_priority_class",
                displaypriorityclass_enum,
                nullable=False,
            ),
        )
        op.add_column(
            "drug_attr_field_definition",
            sa.Column("field_icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
        op.add_column(
            "drug_attr_field_definition",
            sa.Column("field_display_sort_order", sa.Integer(), nullable=True),
        )
        op.add_column(
            "drug_code_system",
            sa.Column("code_icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
        op.add_column(
            "drug_code_system",
            sa.Column("code_display_sort_order", sa.Integer(), nullable=True),
        )
        # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###

        with op.batch_alter_table(
            "drug_attr_field_definition", recreate="always"
        ) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "field_display_priority_class",
                    sa.Enum("CLASS1", "CLASS2", "CLASS3", name="displaypriorityclass"),
                    nullable=False,
                    default="CLASS3",
                    server_default="CLASS3",
                ),
            )

            batch_op.add_column(
                sa.Column(
                    "field_icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True
                ),
            )
            batch_op.add_column(
                sa.Column("field_display_sort_order", sa.Integer(), nullable=True),
            )
            with op.batch_alter_table(
                "drug_code_system", recreate="always"
            ) as batch_op:
                batch_op.add_column(
                    sa.Column(
                        "code_icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True
                    ),
                )
                batch_op.add_column(
                    sa.Column("code_display_sort_order", sa.Integer(), nullable=True),
                )
        # ### end Alembic commands ###
    else:
        raise NotImplementedError(
            f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'"
        )


def downgrade():
    raise NotImplementedError(f"DZDMedLog does not support downgrading the database")
