"""Automated migration: another day of wip #149

Revision ID: 37f744a13abb
Revises: 8cbe84016acb
Create Date: 2025-11-27 20:18:12.251235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = "37f744a13abb"
down_revision: Union[str, Sequence[str], None] = "8cbe84016acb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column(
            "drug_attr_field_lov_item",
            sa.Column("drug_dataset_version_fk", sa.Uuid(), nullable=False),
        )
        op.create_unique_constraint(
            "unique_lovitem_fielddef",
            "drug_attr_field_lov_item",
            ["importer_name", "field_name", "drug_dataset_version_fk"],
            deferrable=True,
            initially="IMMEDIATE",
        )
        op.drop_constraint(
            op.f("fk_lovitem_fielddef"), "drug_attr_field_lov_item", type_="foreignkey"
        )
        op.create_foreign_key(
            None,
            "drug_attr_field_lov_item",
            "drug_dataset_version",
            ["drug_dataset_version_fk"],
            ["id"],
        )
        op.add_column(
            "drug_code_system",
            sa.Column(
                "importer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
        )
        op.create_unique_constraint(
            "uq_code_system_field_definition__field__importer",
            "drug_code_system",
            ["name", "importer_name"],
        )
        # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table(
            "drug_attr_field_lov_item", recreate="always"
        ) as batch_op:
            batch_op.add_column(
                sa.Column("drug_dataset_version_fk", sa.Uuid(), nullable=False),
            )

            batch_op.create_unique_constraint(
                "unique_lovitem_fielddef",
                ["importer_name", "field_name", "drug_dataset_version_fk"],
            )
            batch_op.drop_constraint(
                op.f("fk_lovitem_fielddef"),
                type_="foreignkey",
            )

            batch_op.create_foreign_key(
                "fk_lovitem_dataset_version",
                "drug_dataset_version",
                ["drug_dataset_version_fk"],
                ["id"],
            )
        with op.batch_alter_table("drug_code_system", recreate="always") as batch_op:
            batch_op.add_column(
                sa.Column(
                    "importer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
                ),
            )
            batch_op.create_unique_constraint(
                "uq_code_system_field_definition__field__importer",
                ["name", "importer_name"],
            )
        # ### end Alembic commands ###
    else:
        raise NotImplementedError(
            f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'"
        )


def downgrade():
    raise NotImplementedError(f"DZDMedLog does not support downgrading the database")
