"""baseline schema

Revision ID: 8b9466483897
Revises: 
Create Date: 2025-11-20 11:04:46.711741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = '8b9466483897'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
            op.create_table('drug_attr_field_definition',
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('field_name_display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('field_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('optional', sa.Boolean(), nullable=False),
            sa.Column('is_reference_list_field', sa.Boolean(), nullable=False),
            sa.Column('is_multi_val_field', sa.Boolean(), nullable=False),
            sa.Column('value_type', sa.Enum('STR', 'INT', 'FLOAT', 'BOOL', 'DATETIME', 'DATE', name='valuetypecasting'), nullable=False),
            sa.Column('show_in_search_results', sa.Boolean(), nullable=False),
            sa.Column('used_for_custom_drug', sa.Boolean(), nullable=False),
            sa.Column('is_large_reference_list', sa.Boolean(), nullable=False),
            sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('has_default', sa.Boolean(), nullable=False),
            sa.Column('default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('searchable', sa.Boolean(), nullable=False),
            sa.Column('pre_parser', sa.Enum('WIDO_GKV_DATE', name='custompreparserfunc'), nullable=True),
            sa.Column('examples', medlogserver.model._utils.SqlStringListAny(), nullable=True),
            sa.PrimaryKeyConstraint('field_name', 'importer_name'),
            sa.UniqueConstraint('field_name', 'importer_name', name='uq_drug_attr_field_definition__field__importer'),
            comment='Definition of dataset specific fields and lookup fields. this is a read only table. The attribute field definitons are defined in code. Any changes on the SQL table rows/values will be overwriten.'
            )
            op.create_table('drug_code_system',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('country', sa.String(), nullable=False),
            sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('optional', sa.Boolean(), nullable=False),
            sa.Column('unique', sa.Boolean(), nullable=False),
            sa.Column('client_visible', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_table('drug_dataset_version',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('dataset_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('dataset_source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('dataset_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('is_custom_drugs_collection', sa.Boolean(), nullable=False),
            sa.Column('current_active', sa.Boolean(), nullable=True),
            sa.Column('import_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('import_status', sa.String(), nullable=True),
            sa.Column('import_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('import_start_datetime_utc', sa.DateTime(), nullable=False),
            sa.Column('import_end_datetime_utc', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            comment='Tracks different version of same drug indexes that were imported'
            )
            op.create_table('study',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
            sa.Column('no_permissions', sa.Boolean(), nullable=False),
            sa.Column('deactivated', sa.Boolean(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_study_display_name'), 'study', ['display_name'], unique=True)
            op.create_index(op.f('ix_study_id'), 'study', ['id'], unique=True)
            op.create_table('user',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
            sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('roles', sa.JSON(), nullable=True),
            sa.Column('deactivated', sa.Boolean(), nullable=False),
            sa.Column('is_email_verified', sa.Boolean(), nullable=False),
            sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
            op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
            op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
            op.create_table('drug',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('source_dataset_id', sa.Uuid(), nullable=False),
            sa.Column('trade_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('market_access_date', sa.Date(), nullable=True),
            sa.Column('market_exit_date', sa.Date(), nullable=True),
            sa.Column('is_custom_drug', sa.Boolean(), nullable=False),
            sa.Column('custom_drug_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('custom_created_by', sa.Uuid(), nullable=True),
            sa.ForeignKeyConstraint(['custom_created_by'], ['user.id'], ),
            sa.ForeignKeyConstraint(['source_dataset_id'], ['drug_dataset_version.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            comment='Tracks different version of same drug indexes that were imported'
            )
            op.create_index(op.f('ix_drug_trade_name'), 'drug', ['trade_name'], unique=False)
            op.create_table('drug_attr_field_lov_item',
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('sort_order', sa.Integer(), nullable=True),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['importer_name', 'field_name'], ['drug_attr_field_definition.importer_name', 'drug_attr_field_definition.field_name'], name='fk_lovitem_fielddef', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('value', 'field_name', 'importer_name'),
            comment='Attr fields lists of values'
            )
            op.create_table('event',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('order_position', sa.Integer(), nullable=True),
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('study_id', sa.Uuid(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name', 'study_id', name='unique_eventname_per_study')
            )
            op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=True)
            op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=False)
            op.create_table('study_permission',
            sa.Column('is_study_viewer', sa.Boolean(), nullable=False),
            sa.Column('is_study_interviewer', sa.Boolean(), nullable=False),
            sa.Column('is_study_admin', sa.Boolean(), nullable=False),
            sa.Column('study_id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('study_id', 'user_id', name='One permission entry per user/study only')
            )
            op.create_index(op.f('ix_study_permission_id'), 'study_permission', ['id'], unique=True)
            op.create_table('user_auth',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('auth_source_type', sa.Enum('basic', 'oidc', 'api_token', name='allowedauthschemetype'), nullable=True),
            sa.Column('oidc_provider_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('api_token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('api_token_source_user_auth_id', sa.Uuid(), nullable=True),
            sa.Column('expires_at_epoch_time', sa.Integer(), nullable=True),
            sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('revoked', sa.Boolean(), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('basic_password_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('api_token_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('oidc_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=True)
            op.create_index(op.f('ix_user_auth_oidc_provider_slug'), 'user_auth', ['oidc_provider_slug'], unique=False)
            op.create_table('worker_job',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('run_started_at', sa.DateTime(), nullable=True),
            sa.Column('run_finished_at', sa.DateTime(), nullable=True),
            sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('last_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('task_params', medlogserver.model._utils.SqlJsonText(), nullable=True),
            sa.Column('user_id', sa.Uuid(), nullable=True),
            sa.Column('tags', medlogserver.model._utils.SqlStringListText(), nullable=True),
            sa.Column('interval_params', medlogserver.model._utils.SqlJsonText(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_worker_job_id'), 'worker_job', ['id'], unique=True)
            op.create_table('drug_attr_multi_ref_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value_index', sa.Integer(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_multi_ref_val__field_def', initially='IMMEDIATE', deferrable=True),
            sa.ForeignKeyConstraint(['field_name', 'value', 'importer_name'], ['drug_attr_field_lov_item.field_name', 'drug_attr_field_lov_item.value', 'drug_attr_field_lov_item.importer_name'], name='composite_foreign_key_drug_attr_multi_ref_val__lov_item', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name', 'value_index'),
            comment='Definition of dataset specific fields and lookup fields'
            )
            op.create_table('drug_attr_multi_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value_index', sa.Integer(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_multi_val_field_def', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name', 'value_index'),
            comment='Actual single value of a multi/list attribute  for a drug'
            )
            op.create_table('drug_attr_ref_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_ref_val_field_def', initially='IMMEDIATE', deferrable=True),
            sa.ForeignKeyConstraint(['field_name', 'value', 'importer_name'], ['drug_attr_field_lov_item.field_name', 'drug_attr_field_lov_item.value', 'drug_attr_field_lov_item.importer_name'], name='composite_foreign_key_drug_attr_ref_val__lov_item', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name'),
            comment='Definition of dataset specific fields and lookup fields'
            )
            op.create_table('drug_attr_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_val_field_def', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name'),
            comment='Actual attribute value for a drug'
            )
            op.create_table('drug_code',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('code_system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['code_system_id'], ['drug_code_system.id'], ),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
            sa.PrimaryKeyConstraint('id', 'drug_id', 'code_system_id'),
            comment='Tracks different version of same drug indexes that were imported'
            )
            op.create_table('interview',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('interview_start_time_utc', sa.DateTime(), nullable=False),
            sa.Column('interview_end_time_utc', sa.DateTime(), nullable=True),
            sa.Column('proband_has_taken_meds', sa.Boolean(), nullable=False),
            sa.Column('proband_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('event_id', sa.Uuid(), nullable=False),
            sa.Column('interviewer_user_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
            sa.ForeignKeyConstraint(['interviewer_user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=True)
            op.create_table('user_session',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('user_auth_id', sa.Uuid(), nullable=False),
            sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('expires_at_epoch_time', sa.Integer(), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['user_auth_id'], ['user_auth.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_user_session_id'), 'user_session', ['id'], unique=True)
            op.create_table('intake',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('source_of_drug_information', sa.Enum('DRUG_PACK_SCANNED_PZN', 'DRUG_PACK_TYPED_PZN', 'DRUG_PACK_NAME', 'DRUG_LEAFLET', 'MEDICATION_PLAN', 'PRESCRIPTION', 'PARTICIPANT_SPECIFICATION', 'FOLLOW_UP_PZN', 'FOLLOW_UP_DRUG_NAME', name='sourceofdruginformationanwers'), nullable=True),
            sa.Column('intake_start_time_utc', sa.Date(), nullable=False),
            sa.Column('intake_end_time_utc', sa.Date(), nullable=True),
            sa.Column('administered_by_doctor', sa.Enum('PRESCRIBED', 'RECOMMENDED', 'NO', 'UNKNOWN', name='administeredbydoctoranswers'), nullable=True),
            sa.Column('intake_regular_or_as_needed', sa.Enum('REGULAR', 'ASNEEDED', name='intakeregularorasneededanswers'), nullable=True),
            sa.Column('dose_per_day', sa.Integer(), nullable=True),
            sa.Column('regular_intervall_of_daily_dose', sa.Enum('UNKNOWN', 'DAILY', 'EVERY_SECOND_DAY', 'EVERY_THIRD_DAY', 'EVERY_FOURTH_DAY', 'ONE_WEEK_OR_MORE', 'ONE_MONTH_OR_MORE', 'ONE_YEAR_OR_MORE', name='intervalofdailydoseanswers'), nullable=True),
            sa.Column('as_needed_dose_unit', sa.Integer(), nullable=True),
            sa.Column('consumed_meds_today', sa.Enum('YES', 'NO', 'UNKNOWN', name='consumedmedstodayanswers'), nullable=False),
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('interview_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
            sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_intake_id'), 'intake', ['id'], unique=True)
            # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
            op.create_table('drug_attr_field_definition',
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('field_name_display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('field_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('optional', sa.Boolean(), nullable=False),
            sa.Column('is_reference_list_field', sa.Boolean(), nullable=False),
            sa.Column('is_multi_val_field', sa.Boolean(), nullable=False),
            sa.Column('value_type', sa.Enum('STR', 'INT', 'FLOAT', 'BOOL', 'DATETIME', 'DATE', name='valuetypecasting'), nullable=False),
            sa.Column('show_in_search_results', sa.Boolean(), nullable=False),
            sa.Column('used_for_custom_drug', sa.Boolean(), nullable=False),
            sa.Column('is_large_reference_list', sa.Boolean(), nullable=False),
            sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('has_default', sa.Boolean(), nullable=False),
            sa.Column('default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('searchable', sa.Boolean(), nullable=False),
            sa.Column('pre_parser', sa.Enum('WIDO_GKV_DATE', name='custompreparserfunc'), nullable=True),
            sa.Column('examples', medlogserver.model._utils.SqlStringListAny(), nullable=True),
            sa.PrimaryKeyConstraint('field_name', 'importer_name'),
            sa.UniqueConstraint('field_name', 'importer_name', name='uq_drug_attr_field_definition__field__importer'),
            comment='Definition of dataset specific fields and lookup fields. this is a read only table. The attribute field definitons are defined in code. Any changes on the SQL table rows/values will be overwriten.'
            )
            op.create_table('drug_code_system',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('country', sa.String(), nullable=False),
            sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('optional', sa.Boolean(), nullable=False),
            sa.Column('unique', sa.Boolean(), nullable=False),
            sa.Column('client_visible', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_table('drug_dataset_version',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('dataset_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('dataset_source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('dataset_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('is_custom_drugs_collection', sa.Boolean(), nullable=False),
            sa.Column('current_active', sa.Boolean(), nullable=True),
            sa.Column('import_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('import_status', sa.String(), nullable=True),
            sa.Column('import_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('import_start_datetime_utc', sa.DateTime(), nullable=False),
            sa.Column('import_end_datetime_utc', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            comment='Tracks different version of same drug indexes that were imported'
            )
            op.create_table('study',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
            sa.Column('no_permissions', sa.Boolean(), nullable=False),
            sa.Column('deactivated', sa.Boolean(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_study_display_name'), 'study', ['display_name'], unique=True)
            op.create_index(op.f('ix_study_id'), 'study', ['id'], unique=True)
            op.create_table('user',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
            sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('roles', sa.JSON(), nullable=True),
            sa.Column('deactivated', sa.Boolean(), nullable=False),
            sa.Column('is_email_verified', sa.Boolean(), nullable=False),
            sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
            op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
            op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
            op.create_table('drug',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('source_dataset_id', sa.Uuid(), nullable=False),
            sa.Column('trade_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('market_access_date', sa.Date(), nullable=True),
            sa.Column('market_exit_date', sa.Date(), nullable=True),
            sa.Column('is_custom_drug', sa.Boolean(), nullable=False),
            sa.Column('custom_drug_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('custom_created_by', sa.Uuid(), nullable=True),
            sa.ForeignKeyConstraint(['custom_created_by'], ['user.id'], ),
            sa.ForeignKeyConstraint(['source_dataset_id'], ['drug_dataset_version.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            comment='Tracks different version of same drug indexes that were imported'
            )
            op.create_index(op.f('ix_drug_trade_name'), 'drug', ['trade_name'], unique=False)
            op.create_table('drug_attr_field_lov_item',
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('sort_order', sa.Integer(), nullable=True),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['importer_name', 'field_name'], ['drug_attr_field_definition.importer_name', 'drug_attr_field_definition.field_name'], name='fk_lovitem_fielddef', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('value', 'field_name', 'importer_name'),
            comment='Attr fields lists of values'
            )
            op.create_table('event',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('order_position', sa.Integer(), nullable=True),
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('study_id', sa.Uuid(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name', 'study_id', name='unique_eventname_per_study')
            )
            op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=True)
            op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=False)
            op.create_table('study_permission',
            sa.Column('is_study_viewer', sa.Boolean(), nullable=False),
            sa.Column('is_study_interviewer', sa.Boolean(), nullable=False),
            sa.Column('is_study_admin', sa.Boolean(), nullable=False),
            sa.Column('study_id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('study_id', 'user_id', name='One permission entry per user/study only')
            )
            op.create_index(op.f('ix_study_permission_id'), 'study_permission', ['id'], unique=True)
            op.create_table('user_auth',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('auth_source_type', sa.Enum('basic', 'oidc', 'api_token', name='allowedauthschemetype'), nullable=True),
            sa.Column('oidc_provider_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('api_token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('api_token_source_user_auth_id', sa.Uuid(), nullable=True),
            sa.Column('expires_at_epoch_time', sa.Integer(), nullable=True),
            sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('revoked', sa.Boolean(), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('basic_password_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('api_token_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('oidc_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=True)
            op.create_index(op.f('ix_user_auth_oidc_provider_slug'), 'user_auth', ['oidc_provider_slug'], unique=False)
            op.create_table('worker_job',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('run_started_at', sa.DateTime(), nullable=True),
            sa.Column('run_finished_at', sa.DateTime(), nullable=True),
            sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('last_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('task_params', medlogserver.model._utils.SqlJsonText(), nullable=True),
            sa.Column('user_id', sa.Uuid(), nullable=True),
            sa.Column('tags', medlogserver.model._utils.SqlStringListText(), nullable=True),
            sa.Column('interval_params', medlogserver.model._utils.SqlJsonText(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_worker_job_id'), 'worker_job', ['id'], unique=True)
            op.create_table('drug_attr_multi_ref_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value_index', sa.Integer(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_multi_ref_val__field_def', initially='IMMEDIATE', deferrable=True),
            sa.ForeignKeyConstraint(['field_name', 'value', 'importer_name'], ['drug_attr_field_lov_item.field_name', 'drug_attr_field_lov_item.value', 'drug_attr_field_lov_item.importer_name'], name='composite_foreign_key_drug_attr_multi_ref_val__lov_item', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name', 'value_index'),
            comment='Definition of dataset specific fields and lookup fields'
            )
            op.create_table('drug_attr_multi_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value_index', sa.Integer(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_multi_val_field_def', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name', 'value_index'),
            comment='Actual single value of a multi/list attribute  for a drug'
            )
            op.create_table('drug_attr_ref_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_ref_val_field_def', initially='IMMEDIATE', deferrable=True),
            sa.ForeignKeyConstraint(['field_name', 'value', 'importer_name'], ['drug_attr_field_lov_item.field_name', 'drug_attr_field_lov_item.value', 'drug_attr_field_lov_item.importer_name'], name='composite_foreign_key_drug_attr_ref_val__lov_item', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name'),
            comment='Definition of dataset specific fields and lookup fields'
            )
            op.create_table('drug_attr_val',
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('importer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['field_name', 'importer_name'], ['drug_attr_field_definition.field_name', 'drug_attr_field_definition.importer_name'], name='composite_foreign_key_drug_attr_val_field_def', initially='IMMEDIATE', deferrable=True),
            sa.PrimaryKeyConstraint('drug_id', 'field_name'),
            comment='Actual attribute value for a drug'
            )
            op.create_table('drug_code',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('code_system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(['code_system_id'], ['drug_code_system.id'], ),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
            sa.PrimaryKeyConstraint('id', 'drug_id', 'code_system_id'),
            comment='Tracks different version of same drug indexes that were imported'
            )
            op.create_table('interview',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('interview_start_time_utc', sa.DateTime(), nullable=False),
            sa.Column('interview_end_time_utc', sa.DateTime(), nullable=True),
            sa.Column('proband_has_taken_meds', sa.Boolean(), nullable=False),
            sa.Column('proband_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('event_id', sa.Uuid(), nullable=False),
            sa.Column('interviewer_user_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
            sa.ForeignKeyConstraint(['interviewer_user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=True)
            op.create_table('user_session',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('user_auth_id', sa.Uuid(), nullable=False),
            sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('expires_at_epoch_time', sa.Integer(), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['user_auth_id'], ['user_auth.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_user_session_id'), 'user_session', ['id'], unique=True)
            op.create_table('intake',
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('source_of_drug_information', sa.Enum('DRUG_PACK_SCANNED_PZN', 'DRUG_PACK_TYPED_PZN', 'DRUG_PACK_NAME', 'DRUG_LEAFLET', 'MEDICATION_PLAN', 'PRESCRIPTION', 'PARTICIPANT_SPECIFICATION', 'FOLLOW_UP_PZN', 'FOLLOW_UP_DRUG_NAME', name='sourceofdruginformationanwers'), nullable=True),
            sa.Column('intake_start_time_utc', sa.Date(), nullable=False),
            sa.Column('intake_end_time_utc', sa.Date(), nullable=True),
            sa.Column('administered_by_doctor', sa.Enum('PRESCRIBED', 'RECOMMENDED', 'NO', 'UNKNOWN', name='administeredbydoctoranswers'), nullable=True),
            sa.Column('intake_regular_or_as_needed', sa.Enum('REGULAR', 'ASNEEDED', name='intakeregularorasneededanswers'), nullable=True),
            sa.Column('dose_per_day', sa.Integer(), nullable=True),
            sa.Column('regular_intervall_of_daily_dose', sa.Enum('UNKNOWN', 'DAILY', 'EVERY_SECOND_DAY', 'EVERY_THIRD_DAY', 'EVERY_FOURTH_DAY', 'ONE_WEEK_OR_MORE', 'ONE_MONTH_OR_MORE', 'ONE_YEAR_OR_MORE', name='intervalofdailydoseanswers'), nullable=True),
            sa.Column('as_needed_dose_unit', sa.Integer(), nullable=True),
            sa.Column('consumed_meds_today', sa.Enum('YES', 'NO', 'UNKNOWN', name='consumedmedstodayanswers'), nullable=False),
            sa.Column('drug_id', sa.Uuid(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('interview_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
            sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_intake_id'), 'intake', ['id'], unique=True)
            # ### end Alembic commands ###
    else:
        raise NotImplementedError(f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'") 


def downgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific downgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
            op.drop_index(op.f('ix_intake_id'), table_name='intake')
            op.drop_table('intake')
            op.drop_index(op.f('ix_user_session_id'), table_name='user_session')
            op.drop_table('user_session')
            op.drop_index(op.f('ix_interview_id'), table_name='interview')
            op.drop_table('interview')
            op.drop_table('drug_code')
            op.drop_table('drug_attr_val')
            op.drop_table('drug_attr_ref_val')
            op.drop_table('drug_attr_multi_val')
            op.drop_table('drug_attr_multi_ref_val')
            op.drop_index(op.f('ix_worker_job_id'), table_name='worker_job')
            op.drop_table('worker_job')
            op.drop_index(op.f('ix_user_auth_oidc_provider_slug'), table_name='user_auth')
            op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
            op.drop_table('user_auth')
            op.drop_index(op.f('ix_study_permission_id'), table_name='study_permission')
            op.drop_table('study_permission')
            op.drop_index(op.f('ix_event_name'), table_name='event')
            op.drop_index(op.f('ix_event_id'), table_name='event')
            op.drop_table('event')
            op.drop_table('drug_attr_field_lov_item')
            op.drop_index(op.f('ix_drug_trade_name'), table_name='drug')
            op.drop_table('drug')
            op.drop_index(op.f('ix_user_user_name'), table_name='user')
            op.drop_index(op.f('ix_user_id'), table_name='user')
            op.drop_index(op.f('ix_user_email'), table_name='user')
            op.drop_table('user')
            op.drop_index(op.f('ix_study_id'), table_name='study')
            op.drop_index(op.f('ix_study_display_name'), table_name='study')
            op.drop_table('study')
            op.drop_table('drug_dataset_version')
            op.drop_table('drug_code_system')
            op.drop_table('drug_attr_field_definition')
            # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific downgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
            op.drop_index(op.f('ix_intake_id'), table_name='intake')
            op.drop_table('intake')
            op.drop_index(op.f('ix_user_session_id'), table_name='user_session')
            op.drop_table('user_session')
            op.drop_index(op.f('ix_interview_id'), table_name='interview')
            op.drop_table('interview')
            op.drop_table('drug_code')
            op.drop_table('drug_attr_val')
            op.drop_table('drug_attr_ref_val')
            op.drop_table('drug_attr_multi_val')
            op.drop_table('drug_attr_multi_ref_val')
            op.drop_index(op.f('ix_worker_job_id'), table_name='worker_job')
            op.drop_table('worker_job')
            op.drop_index(op.f('ix_user_auth_oidc_provider_slug'), table_name='user_auth')
            op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
            op.drop_table('user_auth')
            op.drop_index(op.f('ix_study_permission_id'), table_name='study_permission')
            op.drop_table('study_permission')
            op.drop_index(op.f('ix_event_name'), table_name='event')
            op.drop_index(op.f('ix_event_id'), table_name='event')
            op.drop_table('event')
            op.drop_table('drug_attr_field_lov_item')
            op.drop_index(op.f('ix_drug_trade_name'), table_name='drug')
            op.drop_table('drug')
            op.drop_index(op.f('ix_user_user_name'), table_name='user')
            op.drop_index(op.f('ix_user_id'), table_name='user')
            op.drop_index(op.f('ix_user_email'), table_name='user')
            op.drop_table('user')
            op.drop_index(op.f('ix_study_id'), table_name='study')
            op.drop_index(op.f('ix_study_display_name'), table_name='study')
            op.drop_table('study')
            op.drop_table('drug_dataset_version')
            op.drop_table('drug_code_system')
            op.drop_table('drug_attr_field_definition')
            # ### end Alembic commands ###
    else:
        raise NotImplementedError(f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'") 