"""Automated migration: complete #182

Revision ID: 8cbe84016acb
Revises: 328eaf68f1a1
Create Date: 2025-11-24 15:40:49.663033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = "8cbe84016acb"
down_revision: Union[str, Sequence[str], None] = "328eaf68f1a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column(
            "drug_dataset_version",
            sa.Column("import_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
        op.add_column(
            "drug_dataset_version",
            sa.Column("activated_date_datetime_utc", sa.DateTime(), nullable=True),
        )
        op.add_column(
            "drug_dataset_version",
            sa.Column("disabled_date_datetime_utc", sa.DateTime(), nullable=True),
        )
        op.add_column(
            "drug_dataset_version",
            sa.Column("cleaned_date_datetime_utc", sa.DateTime(), nullable=True),
        )
        op.alter_column(
            "drug_dataset_version",
            "import_start_datetime_utc",
            existing_type=sa.DATETIME(),
            nullable=True,
        )
        op.drop_column("drug_dataset_version", "import_file_path")
        op.drop_index(op.f("ix_event_name"), table_name="event")
        op.drop_index(op.f("ix_user_user_name"), table_name="user")
        # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###

        with op.batch_alter_table(
            "drug_dataset_version", recreate="always"
        ) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "import_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
                ),
            )

        with op.batch_alter_table(
            "drug_dataset_version", recreate="always"
        ) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "import_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
                ),
            )

            batch_op.add_column(
                sa.Column("activated_date_datetime_utc", sa.DateTime(), nullable=True),
            )
            batch_op.add_column(
                sa.Column("disabled_date_datetime_utc", sa.DateTime(), nullable=True),
            )
            batch_op.add_column(
                sa.Column("cleaned_date_datetime_utc", sa.DateTime(), nullable=True),
            )
            batch_op.alter_column(
                "import_start_datetime_utc",
                existing_type=sa.DATETIME(),
                nullable=True,
            )
            batch_op.drop_column("import_file_path")
        op.drop_index(op.f("ix_event_name"), table_name="event")
        op.drop_index(op.f("ix_user_user_name"), table_name="user")
        # ### end Alembic commands ###
    else:
        raise NotImplementedError(
            f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'"
        )


def downgrade():
    raise NotImplementedError(f"DZDMedLog does not support downgrading the database")
