"""Automated migration: Merge pull request #253 from DZD-eV-Diabetes-Research/fix/issue-252-wrong-search-result-count

WIP #252

Revision ID: d52740e337b2
Revises: a60dae4c25ee
Create Date: 2026-03-25 14:56:30.275872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = 'd52740e337b2'
down_revision: Union[str, Sequence[str], None] = 'a60dae4c25ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
            op.create_table('appstate',
            sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.PrimaryKeyConstraint('key')
            )
            # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
            op.create_table('appstate',
            sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.PrimaryKeyConstraint('key')
            )
            # ### end Alembic commands ###
    else:
        raise NotImplementedError(f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'") 


def downgrade():
        raise NotImplementedError(f"DZDMedLog does not support downgrading the database")