"""Automated migration: possible fix for #176

Revision ID: f5d8639f63da
Revises: 8915b8abf3fe
Create Date: 2025-12-09 10:03:52.518723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import medlogserver.model._utils


# revision identifiers, used by Alembic.
revision: str = "f5d8639f63da"
down_revision: Union[str, Sequence[str], None] = "8915b8abf3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        # --- PostgreSQL-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column(
            "intake",
            sa.Column(
                "is_activeingredient_equivalent_choice",
                sa.Boolean(),
                nullable=False,
                default=True,
            ),
        )
        # ### end Alembic commands ###
    elif dialect == "sqlite":
        # --- SQLite-specific upgrade ---
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column(
            "intake",
            sa.Column(
                "is_activeingredient_equivalent_choice",
                sa.Boolean(),
                nullable=False,
                default=True,
            ),
        )
        # ### end Alembic commands ###
    else:
        raise NotImplementedError(
            f"DZDMedLog only supports Postgres (and SQlite for local development). Please use another database as '{dialect}'"
        )


def downgrade():
    raise NotImplementedError(f"DZDMedLog does not support downgrading the database")
