name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - dev

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get git tags

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DZD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DZD_PASSWORD }}

      - name: Set dynamic Docker tag for dev branch
        if: github.ref == 'refs/heads/dev'
        id: devtag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "DEV_TAG=${LAST_TAG}-${SHORT_SHA}-dev" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dzdde/dzdmedlog

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.devtag.outputs.DEV_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker Hub Description
        if: github.event_name == 'release'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_DZD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DZD_PASSWORD }}
          repository: dzdde/dzdmedlog
          short-description: "The server module for DZDMedLog, a system to document the medical history of study participant."
          enable-url-completion: true
          readme-filepath: "DOCKERHUB_README.md"
