name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - dev

jobs:
  push_prod_release_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DZD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DZD_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dzdde/dzdmedlog

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_DZD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DZD_PASSWORD }}
          repository: dzdde/dzdmedlog
          short-description: "The server module for DZDMedLog, a system to document the medical history of study participant."
          enable-url-completion: true
          readme-filepath: "DOCKERHUB_README.md"

  push_dev_commit_image:
    name: Build and tag dev image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important! to get the tag list

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DZD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DZD_PASSWORD }}

      - name: Extract version from __version__.py
        id: get_version
        run: |
          VERSION=$(python3 -c "import re; exec(open('MedLog/backend/medlogserver/__version__.py').read()); print(__version__)")
          SANITIZED_VERSION=${VERSION//+/_}
          echo "version=${SANITIZED_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image (dev)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            dzdde/dzdmedlog:${{ steps.get_tag.outputs.version }}
            dzdde/dzdmedlog:dev
