/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ConsumedMedsTodayAnswers.
* @enum {}
* @readonly
*/
export default class ConsumedMedsTodayAnswers {
    
        /**
         * value: "Yes"
         * @const
         */
        "Yes" = "Yes";

    
        /**
         * value: "No"
         * @const
         */
        "No" = "No";

    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    

    /**
    * Returns a <code>ConsumedMedsTodayAnswers</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ConsumedMedsTodayAnswers} The enum <code>ConsumedMedsTodayAnswers</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

