/**
 * MedLog REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Generikakennung model module.
 * @module model/Generikakennung
 * @version 0.0.1
 */
class Generikakennung {
    /**
     * Constructs a new <code>Generikakennung</code>.
     * @alias module:model/Generikakennung
     * @param generikakenn {Number} generikakenn id
     * @param bedeutung {String} Bedeutung
     */
    constructor(generikakenn, bedeutung) { 
        
        Generikakennung.initialize(this, generikakenn, bedeutung);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, generikakenn, bedeutung) { 
        obj['generikakenn'] = generikakenn;
        obj['bedeutung'] = bedeutung;
    }

    /**
     * Constructs a <code>Generikakennung</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Generikakennung} obj Optional instance to populate.
     * @return {module:model/Generikakennung} The populated <code>Generikakennung</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Generikakennung();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('generikakenn')) {
                obj['generikakenn'] = ApiClient.convertToType(data['generikakenn'], 'Number');
            }
            if (data.hasOwnProperty('bedeutung')) {
                obj['bedeutung'] = ApiClient.convertToType(data['bedeutung'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Generikakennung</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Generikakennung</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Generikakennung.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bedeutung'] && !(typeof data['bedeutung'] === 'string' || data['bedeutung'] instanceof String)) {
            throw new Error("Expected the field `bedeutung` to be a primitive type in the JSON string but got " + data['bedeutung']);
        }

        return true;
    }


}

Generikakennung.RequiredProperties = ["generikakenn", "bedeutung"];

/**
 * @member {Date} created_at
 */
Generikakennung.prototype['created_at'] = undefined;

/**
 * generikakenn id
 * @member {Number} generikakenn
 */
Generikakennung.prototype['generikakenn'] = undefined;

/**
 * Bedeutung
 * @member {String} bedeutung
 */
Generikakennung.prototype['bedeutung'] = undefined;






export default Generikakennung;

